export const ROUTES = {
    root: '/content-admin',
    login: '/content-admin/login',
    paymentSystems: '/content-admin/payment-systems',
    currency: '/content-admin/currency',
    currencyGenerals: (id: number | undefined) => `/content-admin/currency/generals/${id || ':id'}`,
    currencyCode: '/content-admin/currecy_code',
    exchangeDirections: '/content-admin/exchange-directions',
    payouts: {
        index: '/content-admin/payouts/all',
        waitingRequisites: '/content-admin/payouts/waiting-for-requisites',
        givenRequisistes: '/content-admin/payouts/given-requisites',
        preliminary: '/content-admin/payouts/preliminary',
        process: '/content-admin/payouts/process',
        completed: '/content-admin/payouts/completed',
        rejected: '/content-admin/payouts/rejected',
        error: '/content-admin/payouts/error',
        referralPay: 'content-admin/payouts/referral-pay',
    },
    payout: (payouId?: number | undefined) => `/content-admin/payouts/${payouId || ':id'}`,
    additionalFields: '/content-admin/additional-fields',
    requisites: '/content-admin/requisites',
    settings: '/content-admin/settings',
    autobroker: '/content-admin/autobroker',
};
